apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/jojo/projects/food-delivery/mongo/data
