# BASE 64 ENCODING
#
# echo "supercalifragilistico" | base64 
# after encoding it, this becomes c3VwZXJjYWxpZnJhZ2lsaXN0aWNvCg==
#
# echo "c3VwZXJjYWxpZnJhZ2lsaXN0aWNvCg==" | base64 --decode
# after decoding it, this will give supercalifragilistico
#
# username: adminuser
# password: password123

apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM=
  username: YWRtaW51c2Vy
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds